### PR TITLE
add file upload func.

### PR DESCRIPTION
**Pull request by YenanHHH**
add Serializing and Deserializing JSON part.
fixed some bugs < sometimes array index is out of range>

Signed-off-by: yenan Huang <yenan.huang@kcl.ac.uk>

### CODE REVIEW

**Comment by dietc** [comment]
Have you finished this function?

**Comment by YenanHHH** [comment]
yes, for upload part, it is done :)
and i will continue optimizing some algorithms, and will update my codes soon!

**Comment by YenanHHH** [comment]
Plus, I added Newtonsoft.Json to serialize and deserialize JSON Data.

**Comment by k1800566** [comment]
Ok i have checked your code and will focus on my code with Gson.

**Comment by YenanHHH** [comment]
> Ok i have checked your code and will focus on my code with Gson.

keep going, BTW remember to correct the mistakes, if it helps, then great :) .

**Comment by dietc** [comment]
perfect!

**Pull request merged**
